// Enums and constants

const RISK_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
};

const IMPACT_LEVELS = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
};

const NEWS_CATEGORIES = {
  RBI_POLICY: 'RBI_POLICY',
  INFLATION: 'INFLATION',
  MARKET_EVENT: 'MARKET_EVENT',
  INTEREST_RATE: 'INTEREST_RATE',
  CURRENCY: 'CURRENCY',
  OTHER: 'OTHER'
};

const RISK_APPETITE = {
  CONSERVATIVE: 'CONSERVATIVE',
  MODERATE: 'MODERATE',
  AGGRESSIVE: 'AGGRESSIVE'
};

const LOAN_TYPES = {
  HOME_LOAN: 'HOME_LOAN',
  PERSONAL_LOAN: 'PERSONAL_LOAN',
  CAR_LOAN: 'CAR_LOAN',
  EDUCATION_LOAN: 'EDUCATION_LOAN',
  CREDIT_CARD: 'CREDIT_CARD'
};

const SUBSCRIPTION_PLANS = {
  FREE: 'FREE',
  PREMIUM: 'PREMIUM'
};

const SUBSCRIPTION_STATUS = {
  ACTIVE: 'ACTIVE',
  EXPIRED: 'EXPIRED',
  CANCELLED: 'CANCELLED'
};

const NOTIFICATION_TYPES = {
  EMAIL: 'EMAIL',
  SMS: 'SMS',
  PUSH: 'PUSH'
};

const NOTIFICATION_PRIORITY = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH'
};

// Risk calculation weights
const RISK_WEIGHTS = {
  NEWS_IMPACT: 0.3,
  LOAN_EXPOSURE: 0.25,
  EXPENSE_RATIO: 0.25,
  RISK_APPETITE: 0.2
};

// Risk score thresholds
const RISK_THRESHOLDS = {
  LOW: 30,
  MEDIUM: 60
};

module.exports = {
  RISK_LEVELS,
  IMPACT_LEVELS,
  NEWS_CATEGORIES,
  RISK_APPETITE,
  LOAN_TYPES,
  SUBSCRIPTION_PLANS,
  SUBSCRIPTION_STATUS,
  NOTIFICATION_TYPES,
  NOTIFICATION_PRIORITY,
  RISK_WEIGHTS,
  RISK_THRESHOLDS
};

